import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import cloudinary from "cloudinary";
import { Folder } from "./albums/page";
import ToggleMode from "../components/ToggleMode";
import Header from "../components/Header";
import Logo from "../components/Logo"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "OUTBREAK | Photo Album",
  description: "Generated by create next app",
};

async function SideMenu() {
  const { folders } = (await cloudinary.v2.api.root_folders()) as {
    folders: Folder[];
  };

  return (
    <div className="pb-12 w-1/3 mt-10">
      <div className="space-y-1 py-4">
        <div className="space-y-1">
          <Header />
        </div>
      </div>
    </div>
  );
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark" suppressHydrationWarning>
      <body className={inter.className}>
        <div className="border-b mx-12 border-gray-700 dark:border-gray-400">
          <div className="flex h-20 items-center px-4 mt-3 container mx-auto">
            <Link href="/">
              <Logo />
            </Link>
            <div className="flex items-center justify-evenly w-full">
              <SideMenu />
            </div>
            <div className="ml-auto flex items-center border-2 border-solid rounded-lg border-black bg-white dark:border-white  dark:bg-black">
              <ToggleMode />
            </div>
          </div>
        </div>
        <div className="w-full pl-12 px-4 pt-8">{children}</div>
      </body>
    </html>
  );
}
